### ISSUE TITLE
The Cloud Storage notification continues to be displayed in the main window, after downloading a file and selecting a provider in a new one

### ISSUE THREAD

**Issue by SoftVision-CosminMuntean** [mozilla/shield-cloudstorage#46]
[Affected versions]:
- Firefox 60.0.2 (Unbranded build)

[Affected Platforms]:
- All Windows
- All Mac
- All Linux

[Prerequisites]:
- The "xpinstall.signatures.required" boolean pref is set to "false".
- The "extensions.legacy.enabled" boolean pref is set tot "true".
- Have the latest CloudStorage add-on installed.
- Have the Google Drive and Dropbox providers installed on you computer.

[Steps to reproduce]:
1. Start the Firefox browser with the profile from prerequisites.
2. Navigate to "https://www.mozilla.org/en-US/firefox/all/" page and download any file.
3. Open a new window and download any file from "https://www.mozilla.org/en-US/firefox/all/".
4. Choose any of the available providers from the Cloud Storage notification.
5. Click the "Save" button.
6. Focus the main window and navigate to "https://www.mozilla.org/en-US/firefox/all/" page.
7. Download any file and click the "Downlod" button from browser toolbar.
8. Observe the download panel.

[Expected result]:
- The Cloud Storage notification is no longer displayed.

[Actual result]:
- The Cloud Storage notification is displayed.

[Notes]:
- Here is a screen recording with the issue: https://goo.gl/Q6Me8z

**Comment by punamdahiya** [comment]
This issue is specific to use case when user opens multiple windows. In this version of extension, the user has to explicitly dismiss the notification once its shown. We are not supporting auto hide of notification displayed and ignored in a previously opened window. 

Considering we have interval of 1 or 2 days between showing subsequent notification, my take this is an edge case that should not impact study. Thanks!
