### ISSUE TITLE
[Intermittent] "Move to Dropbox" functionality sometimes fails moving the files to the Dropbox folder on Windows

### ISSUE THREAD

**Issue by Softvision-PatriciuPop** [mozilla/shield-cloudstorage#52]
[Affected versions]:
- Firefox 60.0.2
- Firefox 61.0

[Affected Platforms]:
- Windows 10 x64
- Windows 7 x64

[Prerequisites]:
- Have Dropbox installed on you computer.
- Have the Dropbox folder open.

[Steps to reproduce]:
1. Start the browser with a new profile and install the latest Cloud Storage version (5.0.2).
2. Navigate to the https://www.thinkbroadband.com/download page.
3. Download any 3 files. (eg. 5MB, 10MB, 20MB)
4. Click on the Download icon from the browser toolbar.
5. Right click and select the "Move to Dropbox" option for each downloaded file.
6. Observe the files from the download panel.
7. Focus the Dropbox folder and observe the moved files.

[Expected result]:
Step 6: - The files have the Dropbox icon.
Step 7: - The files are successfully moved to the Dropbox folder.

[Actual result]:
Step 6: - Some files do not have the Dropbox icon.
Step 7: - The files without the Dropbox icon are not successfully moved and 0 KB copies of them are created instead.

[Notes]:
- This issue is not reproducible on Ubuntu or Mac.
- This issue is not reproducible with Google Drive and having it installed does not affect the bug.
- This issue appears randomly without a pattern.
- Here is a screenshot with browser console errors:
![console](https://user-images.githubusercontent.com/40393891/41984659-dcb7e9c0-7a39-11e8-895f-0f9bcd2943ca.png)

- Here is a screenrecording of the issue:
![move to dropbox](https://user-images.githubusercontent.com/40393891/41984653-d82d161e-7a39-11e8-9319-76bf5bffa2bd.gif)

- Here is a screenshot of the Dropbox folder:
![dropbox folder](https://user-images.githubusercontent.com/40393891/41984648-d3e64922-7a39-11e8-9c37-ec98915f66c9.png)

**Comment by punamdahiya** [comment]
@Softvision-PatriciuPop Its definitely intermittent, I tried replicating it on windows following the steps and was able to move downloads between folder successfully. 
The error indicates failure in the move call because of Access denied error which looks an edge case and that's why hard to replicate.  The fix should be handling such edge cases gracefully by 
a) either not leaving an empty copy of file in destination folder because of failed move and showing user move download failed message on UI.
b) or if possible preemptively Hide Move download in context menu by checking if destination folder cannot be accessed.

Considering its an intermittent error, It should not impact study feedback and is not a blocker. Marking it stretch to handle such failures gracefully.
